### ISSUE TITLE
global notes section for player reference

### ISSUE THREAD

**Issue by joshdeboer** [joshdeboer/itc-battles-app#22]
Original suggestion: "It would be nice if we could have a notepad that works across all battles where you can keep notes for your army.  Could be reminders to use certain stratagems, or whatever.  A notepad with the ability to attach pictures would be great addition.  Something that could be viewed during any battle.  Also be able to store multiple notes for different armies."

**Comment by Vayess** [comment]
I see it could be useful. But i wouldn't prioritize it very high. You always can use another app for it...
