### ISSUE TITLE
App on iPhoneXS does not display correctly around notch

### ISSUE THREAD

**Issue by agile-heresy** [joshdeboer/itc-battles-app#29]
The app does not seem to be boundaries to account for the notch in newer iPhones. This makes navigation and tapping the book icon impossible. 
![D89CCE44-E93D-4D80-AC49-FD300ECF44D2](https://user-images.githubusercontent.com/2532074/89975817-bc131a00-dc34-11ea-9e9b-2444efc4cb89.png)

**Comment by joshdeboer** [comment]
Thanks @JCRobertson, I'll see what I can do.

**Comment by joshdeboer** [comment]
Should be fixed in latest update.
