### ISSUE TITLE
App does not support Split View on iPad 

### ISSUE THREAD

**Issue by gbohnen** [joshdeboer/itc-battles-app#33]
Just a suggestion. On iOS 14.4.0, ITC Battles cannot show side-by-side with other apps using Split View. Slide Over seems to work with other apps on top of ITCB, but I can’t transition to Slide View or have ITCB on top of another window.

I think this would be a pretty handy use case for iPad users in landscape mode, especially for rules apps or notes side by side with game tracking.

**Comment by joshdeboer** [comment]
Thanks for the suggestion, I'll take a look and see if this can be done without too much effort.

**Comment by joshdeboer** [comment]
Fixed in version 0.9.14
