### ISSUE TITLE
Suggestion: Conditions and scoring summary for secondaries

### ISSUE THREAD

**Issue by MrBear86** [joshdeboer/itc-battles-app#37]
Would be really handy if you could tap on each of your selected secondaries in the Scoring screen to see a brief bullet-pointed summary (perhaps as a pop-up) of the objective conditions, points and when they are scored. This would really help with the confusion created by the fact that all the different secondaries are scored at different times and sometimes have two different points levels.

Here's an couple of examples of the sort of thing I mean ...

ENGAGE ON ALL FRONTS
Points scored: End of your turn
Conditions:
- 2 points - one or more units wholly within three different table quarters and more than 6" from centre.
- 3 points - one or more units wholly within each table quarter and more than 6" from centre.

RAISE THE BANNERS HIGH
Points scored: End of your Command Phase + end of battle
Conditions:
- Perform "Raise Banners" action on a controlled objective
- 1 point at the end of each of your Command Phases for every objective with a banner
- 1 point at the end of the battle for every objective with a banner remaining
- Banner is removed from an objective if your opponent controls it

**Comment by joshdeboer** [comment]
Thanks for the suggestion. This has been discussed some already and is something that I think should be added. It would have to be made clear to the players that the text isn't the official rule to mitigate people playing it wrong. I think should probably take the form of hints to jog your memory rather than just a rewritten rule.

**Comment by MrBear86** [comment]
Hi,

Yes, I completely agree with you. Just intended as a reminder.

Should be a short-hand summary a bit like the little bullet pointed
summaries of core rules that appear in the BRB. Perhaps you could include
the reference in small print where the full rule can be found?

Other than that, I think the app is really great. I don't play competitive
myself but 9th edition is a bit more admin heavy and I find the app
extremely useful for speeding up my friendly games.

Thanks.

**Comment by joshdeboer** [comment]
Closing because this feature has been added to the app rewrite, Tabletop Battles, and won't be added to ITC Battles.
