### ISSUE TITLE
No tournament games win percentage gives NaN instead of 0%

### ISSUE THREAD

**Issue by agile-heresy** [joshdeboer/itc-battles-app#38]
Very minor, but in the Home Screen in the first carousel on the third slide tournament win % is NaN instead of 0 if no tournament games have been played. Love the app, keep up the excellent work!![image](https://user-images.githubusercontent.com/2532074/128649795-aaea6eec-373e-4414-8dc1-532aa7217d9d.jpeg)

**Comment by joshdeboer** [comment]
Thanks @JCRobertson, I’ll get this fixed in the next update. Glad you’re enjoying the app!

**Comment by joshdeboer** [comment]
Fixed in 0.9.24
