### ISSUE TITLE
Export stats

### ISSUE THREAD

**Issue by datinc** [joshdeboer/itc-battles-app#39]
Would like to see stats for secondaries, primaries, missions etc. Or be able to export games using csv.

**Comment by joshdeboer** [comment]
Thanks @datinc, I’ll look into this and see what can be done.

**Comment by joshdeboer** [comment]
Closing because this feature won't be added to ITC Battles. Please submit feedback for the app rewrite, Tabletop Battles, if this is something you're interested in. Thanks!
