### ISSUE TITLE
Suggestion: bulk clear old games

### ISSUE THREAD

**Issue by MikeEmery** [joshdeboer/itc-battles-app#40]
It would be nice if there was a quick way to clear old games (eg > 3 months old) or to filter the stats based on a date range. I have games from 8th Ed tracked and they don’t mean much for my current performance. 

Thanks for all you do, the app is great.

**Comment by joshdeboer** [comment]
Thanks @MikeEmery, it’s been on my list for a while to separate 8th and 9th games for at least the stats, and I think that’s the place to start. I’ll see what I can do about including it in the next update.

**Comment by joshdeboer** [comment]
Closing because stats can be filtered by edition now.
