### ISSUE TITLE
Feature Request: Android TV Integration

### ISSUE THREAD

**Issue by agile-heresy** [joshdeboer/itc-battles-app#41]
I know this is kind of a ridiculous request, but I figure the worst that can happen is that you say it is too complicated.  I haven't used Vue.js before so I don't know what kind of work would be required to make the app compatible with Android TV, but I personally love to have the scoring tab up on a screen to use as a scoreboard during games that both players can see as it has all the info you could want. Integration with Andoird TV (If not too much of a hassle) would allow me to display the scoreboard much easier than trying to fight with chromecast or hook up a laptop display.

**Comment by joshdeboer** [comment]
Interesting suggestion. I briefly looked at Android TV apps and it looks like it runs native android apps, usually built with Android Studio. So the ITCBA app isn't compatible out of the box and I can't just build it for Android TV. I see the possibly of making a simple Android TV wrapper app that loads the ITCBA web page, but that's not something I can tackle right now. Maybe someone familiar with Android TV could whip something up :)

**Comment by joshdeboer** [comment]
Closing because there wasn't enough demand to justify adding Android TV integration.
