### ISSUE TITLE
Feature Request: Tempest of War

### ISSUE THREAD

**Issue by xcv-** [joshdeboer/itc-battles-app#43]
Primary/secondary scoring works similarly in this format, and I believe that support for it (even if that initially means counting secondary points by hand) would be a nice to have.

Ideally one should be able to select which secondaries were scored each round for how many points, but that's unnecessary. At the very least supporting the different primary missons and a basic counter for secondaries should be a good improvement over nothing!

**Comment by joshdeboer** [comment]
Thanks for the suggestion, we're actually already working on this feature and it will be coming soon!

**Comment by joshdeboer** [comment]
Closing because Tempest of War has been added to the app rewrite, Tabletop Battles, and won't be added to ITC Battles.
