### ISSUE TITLE
Loss of Victory Poins

### ISSUE THREAD

**Issue by Giltharin** [joshdeboer/itc-battles-app#44]
Last night I played Conversion mission that has a rule for player loosing 1 VP if not controlling Owen deployment zone objective and we reduced VP in second primary to account for that, as there seems to be no feature to record VP losses.

A few missions in Nephilin and Nachmund CA include rules for players loosing VP under certain conditions. It would be great to have the possibility to record such losses.
Kind Tegards

Marco

**Comment by joshdeboer** [comment]
Good catch, I'll try to get a fix in the next build to allow for negative values for those few items that need it.

Thanks!

**Comment by joshdeboer** [comment]
Version 0.11.5 now supports negative victory points.
