### ISSUE TITLE
Chaos space Marine secondaries part 2

### ISSUE THREAD

**Issue by xenoterracide** [joshdeboer/itc-battles-app#46]
So I opened an issue about this for eternal War but I realized I should probably enumerate the other ones. Might be a good idea just to make a general pass over all of the books just to ensure that all of the armies have their secondaries. Also for chaos space Marines most sub factions also have their own and I think those are missing everywhere as well too.

At a second glance even missions in eternal War seem to be missing them. Could you please go through and add these objectives to all of the missions/books? Is any more information needed from me?

**Comment by joshdeboer** [comment]
There will be an update released in the next couple days with the CSM codex subfaction secondaries available for Eternal War. I did do a cursory look over the other newer secondaries and I think everything else is good.

Most of the development effort is going into the rewrite, Tabletop Battles, so thanks for pointing out that these were missing.

**Comment by xenoterracide** [comment]
rewrite O.o
